package com.tripbros.server.enumerate;

public enum Country {
	OSAKA, TOKYO, FUKUOKA, OKINAWA, SAPPORO, NAGOYA, BANGKOK, PHUKET, DANANG,
	NHATRANG, HOCHIMINHCITY, HANOI, PHUQUOC, CEBU, MANILA, CLARKFIELD, TAIPEI, SINGAPORE, DENPASAR, HONGKONG,
	KOTAKINABALU, MACAU, SHANGHAI, GUANGZHOU, BEIJING, QINGDAO, SHENZHEN, YANJI, HANGZHOU, XIAMEN, DALIAN, PARIS,
	LONDON, ROME, MILAN, BARCELONA, MADRID, FRANKFURT, MUNICH, ISTANBUL, ZURICH, PRAGUE, BUDAPEST, VIENNA, AMSTERDAM,
	LISBON, WARSAW, HELSINKI, ATHENS, LOSANGELES, HONOLULU, NEWYORK, SANFRANCISCO, SEATTLE, CHICAGO, LASVEGAS,
	WASHINGTON, ATLANTA, NEWARK, VANCOUVER, TORONTO, GUAM, SYDNEY, BRISBANE, MELBOURNE, CAIRNS, PERTH, SAIPAN,
	AUCKLAND, CHRISTCHURCH, QUEENSTOWN, KOROR, CANCUN, MEXICOCITY, MONTERREY, LIMA, SAOPAULO, RIODEJANEIRO, BOGOTA,
	BUENOSAIRES, SANTIAGO, HAVANA, ULAANBAATAR, PHNOMPENH, SIEMREAP, VIENTIANE, MALE, ALMATY, TASHKENT, DELHI, YANGON,
	KATHMANDU, DUBAI, ABUDHABI, TELAVIV, TEHRAN, DOHA, AMMAN, KUWAIT, DAMMAM, JEDDAH, RIYADH, CAIRO, CAPETOWN,
	JOHANNESBURG, KINSHASA, DARESSALAAM, ZANZIBAR, CASABLANCA, NAIROBI, ADDISABABA, ENTEBBE
}
