package com.tripbros.server.enumerate;

public enum Country {
	JAPAN, THAILAND, VIETNAM, PHILIPPINES, TAIWAN, SINGAPORE, INDONESIA, HONGKONG, MALAYSIA, MACAU, CHINA, FRANCE,
	UNITEDKINGDOM, ITALY, SPAIN, GERMANY, TURKEY, SWITZERLAND, CZECHIA, HUNGARY, AUSTRIA, NETHERLANDS, PORTUGAL,
	POLAND, FINLAND, GREECE, UNITEDSTATES, CANADA, GUAM, AUSTRALIA, SAIPAN, NEWZEALAND, PALAU, MEXICO, PERU,
	BRAZIL, COLOMBIA, ARGENTINA, CHILE, CUBA, MONGOLIA, CAMBODIA, LAOS, MALDIVES, KAZAKHSTAN, UZBEKISTAN,
	INDIA, MYANMAR, NEPAL, UNITEDARABEMIRATES, ISRAEL, IRAN, QATAR, JORDAN, KUWAIT, SAUDIARABIA, EGYPT,
	SOUTHAFRICA, CONGO, TANZANIA, MOROCCO, KENYA, ETHIOPIA, UGANDA,
}
